drivers: net: wireless: added support for rtl8822c

diff --git a/build-kernel b/build-kernel
--- a/build-kernel
+++ b/build-kernel
@@ -18,28 +18,63 @@
 
 # Enviromental Variables
 DATE=$(date +"%d.%m.%y")
-OUT_DIR=$(pwd)/out/
+
+OUT_DIR=$(pwd)/out
+
+# Packages required to compile are:
+# bc bison flex build-essential gcc libssl-dev libncurses5-dev
 
 #PATH=$HOME/gcc-arm64/bin:$HOME/gcc-arm/bin:$PATH
-FILENAME=${OUT_DIR}/boot.img
+FILENAME="${OUT_DIR}/boot-${DATE}.img"
 KERNEL_IMAGE="${OUT_DIR}/arch/arm64/boot/Image"
-DTB_FILE="${OUT_DIR}/arch/arm64/boot/dts/rockchip/rk3399-vaaman-01.dtb"
-if [[ "$@" =~ "rockpro"* ]]; then 
+DTB_FILE="${OUT_DIR}/arch/arm64/boot/dts/rockchip/rk3399-rock-pi-4b.dtb"
+
+if [[ "$@" =~ "rockpro"* ]]; then
 	DTB_FILE="${OUT_DIR}/arch/arm64/boot/dts/rockchip/rk3399-rockpro64.dtb"
 fi
 
-if [[ -z "${KEBABS}" ]]; then
-    COUNT="$(grep -c '^processor' /proc/cpuinfo)"
-    export KEBABS="$((COUNT * 2))"
-fi
+# Pack Image into boot image
+function pack_image() {
+	mkfs.vfat -n "boot" -S 512 -C $FILENAME $((50 * 1024))
+
+	if [ -d $(pwd)/extlinux ]; then
+		cp -r $(pwd)/extlinux/ $OUT_DIR
+	else
+		echo "Extlinux directory does not exist!"
+	fi
+
+	cd $OUT_DIR || exit
+
+	if [ -f $(which mmd) ]; then
+		mmd -i $FILENAME ::/extlinux
+		mcopy -i $FILENAME -s $EXTLINUX_CONF ::/extlinux/extlinux.conf
+		mcopy -i $FILENAME -s $KERNEL_IMAGE ::
+		mcopy -i $FILENAME -s $DTB_FILE ::/rk3399-vaaman-rev01.dtb
+	else
+		echo "install mtools!"
+	fi
+}
+
+# Cleanup previous build files
+function cleanup() {
+	if [ -f ${FILENAME} ]; then
+		rm -f ${FILENAME}
+	fi
+	if [ -f ${KERNEL_IMAGE} ]; then
+		rm -f ${KERNEL_IMAGE}
+	fi
+	if [ -f ${DTB_FILE} ]; then
+		rm -f ${DTB_FILE}
+	fi
+	if [ -d ${OUT_DIR}/extlinux ]; then
+		rm -rf ${OUT_DIR}/extlinux
+	fi
+}
 
 ARGS="ARCH=arm64 \
 O=${OUT_DIR} \
 CROSS_COMPILE=aarch64-linux-gnu- \
-CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \
--j${KEBABS}"
-
-export CROSS_COMPILE=aarch64-linux-gnu-
+-j$(nproc --all)"
 
 if [[ "$@" =~ "debian"* ]]; then
 	echo -e "###### USING DEBIAN EXTLINUX CONFIG #####"
@@ -52,31 +87,30 @@ elif [[ "$@" =~ "rockpro"* ]]; then
 	EXTLINUX_CONF=extlinux/rk3399-rockpro.conf
 else
 	echo -e "###### USING MANJARO EXTLINUX CONFIG #####"
-        EXTLINUX_CONF=extlinux/rk3399-manjaro.conf
+	EXTLINUX_CONF=extlinux/rk3399-manjaro.conf
 fi
 
-rm ${KERNEL_IMAGE} ${DTB_FILE} ${FILENAME}
-rm -r ${OUT_DIR}/extlinux/
+# Cleanup previous build
+cleanup
 
 # Make defconfig
-make -j${KEBABS} ${ARGS} defconfig
+make -j$(nproc --all) ${ARGS} defconfig
 
 # Make kernel Image
-make -j${KEBABS} ${ARGS} CC="ccache ${CROSS_COMPILE}gcc" 2>&1 | tee build.log
+if [ -f $(which ccache) ]; then
+	CROSS_COMPILE="aarch64-linux-gnu-"
+	make -j$(nproc --all) ${ARGS} CC="ccache ${CROSS_COMPILE}gcc" 2>&1 | tee build.log
+else
+	make -j$(nproc --all) ${ARGS} 2>&1 | tee build.log
 
-# Pack Image into boot image
-mkfs.vfat -n "boot" -S 512 -C $FILENAME $((50 * 1024))
+fi
 
-cp -vr extlinux $OUT_DIR
+# Create boot image
+pack_image
 
-cd $OUT_DIR
-
-mmd -i $FILENAME ::/extlinux
-mcopy -i $FILENAME -s $EXTLINUX_CONF ::/extlinux/extlinux.conf
-mcopy -i $FILENAME -s $KERNEL_IMAGE ::
-mcopy -i $FILENAME -s $DTB_FILE ::/rk3399-vaaman-rev01.dtb
-
-cd $(pwd) || exit
-
-cp $KERNEL_IMAGE $HOME/out/
-echo "Bootimage is ready to be pulled"
+if [ -f ${FILENAME} ]; then
+	echo "Kernel compiled successfully!"
+	sudo cp -vr ${FILENAME} /home/vegg/rk3399_kernel/out/
+else
+	echo "Kernel build failed!"
+fi
